name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  django:
    runs-on: ubuntu-latest
    env:
      NUXT_PAGE: development
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.5]
        include:
          - db: postgres
            db_port: 5432

    services:
      postgres:
        image: postgres:17.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: hunter2
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Autoflake
      working-directory: ./backend
      run: |
        autoflake --remove-all-unused-imports --recursive .
    - name: Black
      run: |
        black . --check
    - name: Run Tests
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: hunter2
        POSTGRES_NAME: postgres
        POSTGRES_HOST: 127.0.0.1
      working-directory: ./backend
      run: |
        pytest --cov