name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    name: Build naschi.at
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '22.18.0'
      - name: install dependencies
        run: yarn
      - name: lint
        run: yarn lint-no-fix
      - name: mkdir public/media
        run: mkdir public/media
      - name: mkdir src/media
        run: mkdir src/media
      - name: get image-optimizer
        run: curl -L https://github.com/naschidaniel/image-optimizer/releases/download/v0.5.0/image-optimizer-linux --output image-optimizer && chmod +x image-optimizer
      - name: optimize images
        run: yarn optimize-images
      - name: build
        run: yarn build
