on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: release

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    name: Build naschi.at
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn
      - name: build
        run: yarn build
